export { default as Home} from './Home';
export { default as Auth} from './Auth';
export { default as Contact} from './Contact';
export { default as Docs} from './Docs';
export { default as Security} from './Security';
export { default as UserHome} from './UserHome';
export { default as CreatePost} from './CreatePost';
export { default as UserProfile} from './UserProfile';
export { default as PostDetail} from './PostDetail';